// Code generated by ogen, DO NOT EDIT.
package api

type CreateAnnotationRes interface {
	createAnnotationRes()
}

type DeleteAnnotationRes interface {
	deleteAnnotationRes()
}

type GetAnnotationRes interface {
	getAnnotationRes()
}

type GetAnnotationsRes interface {
	getAnnotationsRes()
}

type UpdateAnnotationRes interface {
	updateAnnotationRes()
}
