/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type CreateAnnotationResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * The new annotation
     */
    annotation?: components.Annotation | undefined;
};

/** @internal */
export namespace CreateAnnotationResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        Annotation?: components.Annotation$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateAnnotationResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Annotation: components.Annotation$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Annotation === undefined ? null : { annotation: v.Annotation }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Annotation?: components.Annotation$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateAnnotationResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            annotation: components.Annotation$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.annotation === undefined ? null : { Annotation: v.annotation }),
            };
        });
}
