/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetAnnotationRequest = {
    /**
     * The id of the annotation.
     */
    id: string;
};

export type GetAnnotationResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * The annotation with the given id.
     */
    annotation?: components.Annotation | undefined;
};

/** @internal */
export namespace GetAnnotationRequest$ {
    export type Inbound = {
        id: string;
    };

    export const inboundSchema: z.ZodType<GetAnnotationRequest, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
            };
        });

    export type Outbound = {
        id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetAnnotationRequest> = z
        .object({
            id: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
            };
        });
}

/** @internal */
export namespace GetAnnotationResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        Annotation?: components.Annotation$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetAnnotationResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Annotation: components.Annotation$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Annotation === undefined ? null : { annotation: v.Annotation }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Annotation?: components.Annotation$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetAnnotationResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            annotation: components.Annotation$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.annotation === undefined ? null : { Annotation: v.annotation }),
            };
        });
}
