/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The base annotation, used
 */
export type BaseAnnotation = {
    title?: string | undefined;
    /**
     * The description of the annotation.
     */
    description?: string | undefined;
    /**
     * The time of the annotation.
     */
    time?: Date | undefined;
    /**
     * The end time, use for ranged annotations.
     */
    endTime?: Date | undefined;
    /**
     * The type of the annotation. Can be anything, used for filtering in the UI.
     */
    type?: string | undefined;
    /**
     * A URL attached to the annotation.
     */
    url?: string | undefined;
    /**
     * The datasets the annotation is attached to.
     */
    datasets?: Array<string> | undefined;
};

/** @internal */
export namespace BaseAnnotation$ {
    export type Inbound = {
        title?: string | undefined;
        description?: string | undefined;
        time?: string | undefined;
        endTime?: string | undefined;
        type?: string | undefined;
        url?: string | undefined;
        datasets?: Array<string> | undefined;
    };

    export const inboundSchema: z.ZodType<BaseAnnotation, z.ZodTypeDef, Inbound> = z
        .object({
            title: z.string().optional(),
            description: z.string().optional(),
            time: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            endTime: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            type: z.string().optional(),
            url: z.string().optional(),
            datasets: z.array(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.title === undefined ? null : { title: v.title }),
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.time === undefined ? null : { time: v.time }),
                ...(v.endTime === undefined ? null : { endTime: v.endTime }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.url === undefined ? null : { url: v.url }),
                ...(v.datasets === undefined ? null : { datasets: v.datasets }),
            };
        });

    export type Outbound = {
        title?: string | undefined;
        description?: string | undefined;
        time?: string | undefined;
        endTime?: string | undefined;
        type?: string | undefined;
        url?: string | undefined;
        datasets?: Array<string> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, BaseAnnotation> = z
        .object({
            title: z.string().optional(),
            description: z.string().optional(),
            time: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            endTime: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            type: z.string().optional(),
            url: z.string().optional(),
            datasets: z.array(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.title === undefined ? null : { title: v.title }),
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.time === undefined ? null : { time: v.time }),
                ...(v.endTime === undefined ? null : { endTime: v.endTime }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.url === undefined ? null : { url: v.url }),
                ...(v.datasets === undefined ? null : { datasets: v.datasets }),
            };
        });
}
