// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"axiom-go/internal/utils"
	"time"
)

// BaseAnnotation - The base annotation, used
type BaseAnnotation struct {
	Title *string `json:"title,omitempty"`
	// The description of the annotation.
	Description *string `json:"description,omitempty"`
	// The time of the annotation.
	Time *time.Time `json:"time,omitempty"`
	// The end time, use for ranged annotations.
	EndTime *time.Time `json:"endTime,omitempty"`
	// The type of the annotation. Can be anything, used for filtering in the UI.
	Type *string `json:"type,omitempty"`
	// A URL attached to the annotation.
	URL *string `json:"url,omitempty"`
	// The datasets the annotation is attached to.
	Datasets []string `json:"datasets,omitempty"`
}

func (b BaseAnnotation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BaseAnnotation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *BaseAnnotation) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *BaseAnnotation) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *BaseAnnotation) GetTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.Time
}

func (o *BaseAnnotation) GetEndTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndTime
}

func (o *BaseAnnotation) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *BaseAnnotation) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

func (o *BaseAnnotation) GetDatasets() []string {
	if o == nil {
		return nil
	}
	return o.Datasets
}
