// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"axiom/internal/utils"
)

type CreateDataset struct {
	// Dataset description
	Description *string `default:"" json:"description"`
	// Dataset unique name
	Name string `json:"name"`
}

func (c CreateDataset) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateDataset) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateDataset) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateDataset) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
