// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"axiom/internal/utils"
	"time"
)

type DatasetSpec struct {
	// The RFC3339-formatted time when the dataset was created.
	Created time.Time `json:"created"`
	// Dataset description
	Description string `json:"description"`
	// Dataset ID
	ID string `json:"id"`
	// Unique dataset name
	Name string `json:"name"`
	// Name of the dataset creator
	Who string `json:"who"`
}

func (d DatasetSpec) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DatasetSpec) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DatasetSpec) GetCreated() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Created
}

func (o *DatasetSpec) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *DatasetSpec) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DatasetSpec) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DatasetSpec) GetWho() string {
	if o == nil {
		return ""
	}
	return o.Who
}
