// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type DatasetField struct {
	Description *string `json:"description,omitempty"`
	Hidden      bool    `json:"hidden"`
	Name        string  `json:"name"`
	Type        string  `json:"type"`
	Unit        string  `json:"unit"`
}

func (o *DatasetField) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *DatasetField) GetHidden() bool {
	if o == nil {
		return false
	}
	return o.Hidden
}

func (o *DatasetField) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DatasetField) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *DatasetField) GetUnit() string {
	if o == nil {
		return ""
	}
	return o.Unit
}
