// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Data struct {
}

type Value struct {
}

type EntryGroupAgg struct {
	Data  *Data  `json:"data,omitempty"`
	Op    string `json:"op"`
	Value Value  `json:"value"`
}

func (o *EntryGroupAgg) GetData() *Data {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *EntryGroupAgg) GetOp() string {
	if o == nil {
		return ""
	}
	return o.Op
}

func (o *EntryGroupAgg) GetValue() Value {
	if o == nil {
		return Value{}
	}
	return o.Value
}
