// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Message struct {
	Code     *string `json:"code,omitempty"`
	Count    int64   `json:"count"`
	Msg      string  `json:"msg"`
	Priority string  `json:"priority"`
}

func (o *Message) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *Message) GetCount() int64 {
	if o == nil {
		return 0
	}
	return o.Count
}

func (o *Message) GetMsg() string {
	if o == nil {
		return ""
	}
	return o.Msg
}

func (o *Message) GetPriority() string {
	if o == nil {
		return ""
	}
	return o.Priority
}
