// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"axiom-go/internal/utils"
	"time"
)

// NewAnnotation - A new annotation to create.
type NewAnnotation struct {
	Title *string `json:"title,omitempty"`
	// The description of the annotation.
	Description *string `json:"description,omitempty"`
	// The time of the annotation.
	Time *time.Time `json:"time,omitempty"`
	// The end time, use for ranged annotations.
	EndTime *time.Time `json:"endTime,omitempty"`
	// The type of the annotation. Can be anything, used for filtering in the UI.
	Type string `json:"type"`
	// A URL attached to the annotation.
	URL *string `json:"url,omitempty"`
	// The datasets the annotation is attached to.
	Datasets []string `json:"datasets"`
}

func (n NewAnnotation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NewAnnotation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *NewAnnotation) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *NewAnnotation) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *NewAnnotation) GetTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.Time
}

func (o *NewAnnotation) GetEndTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndTime
}

func (o *NewAnnotation) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *NewAnnotation) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

func (o *NewAnnotation) GetDatasets() []string {
	if o == nil {
		return []string{}
	}
	return o.Datasets
}
