// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Order struct {
	Desc  bool   `json:"desc"`
	Field string `json:"field"`
}

func (o *Order) GetDesc() bool {
	if o == nil {
		return false
	}
	return o.Desc
}

func (o *Order) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}
