// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Projection struct {
	Alias *string `json:"alias,omitempty"`
	Field string  `json:"field"`
}

func (o *Projection) GetAlias() *string {
	if o == nil {
		return nil
	}
	return o.Alias
}

func (o *Projection) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}
