// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type QueryRequestWithOptions struct {
	Aggregations      []Aggregation `json:"aggregations,omitempty"`
	ContinuationToken *string       `json:"continuationToken,omitempty"`
	Cursor            *string       `json:"cursor,omitempty"`
	EndTime           string        `json:"endTime"`
	Filter            *Filter       `json:"filter,omitempty"`
	GroupBy           []string      `json:"groupBy,omitempty"`
	IncludeCursor     *bool         `json:"includeCursor,omitempty"`
	Limit             *int64        `json:"limit,omitempty"`
	Order             []Order       `json:"order,omitempty"`
	Project           []Projection  `json:"project,omitempty"`
	QueryOptions      *QueryOptions `json:"queryOptions,omitempty"`
	// The time resolution of the query’s graph, in seconds. Valid values are
	// the query’s time range /100 at maximum and /1000 at minimum or "auto".
	Resolution string `json:"resolution"`
	// start and end time for the query, these must be specified as RFC3339 strings
	// or using relative time expressions (e.g. now-1h, now-1d, now-1w, etc)
	StartTime     string          `json:"startTime"`
	VirtualFields []VirtualColumn `json:"virtualFields,omitempty"`
}

func (o *QueryRequestWithOptions) GetAggregations() []Aggregation {
	if o == nil {
		return nil
	}
	return o.Aggregations
}

func (o *QueryRequestWithOptions) GetContinuationToken() *string {
	if o == nil {
		return nil
	}
	return o.ContinuationToken
}

func (o *QueryRequestWithOptions) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *QueryRequestWithOptions) GetEndTime() string {
	if o == nil {
		return ""
	}
	return o.EndTime
}

func (o *QueryRequestWithOptions) GetFilter() *Filter {
	if o == nil {
		return nil
	}
	return o.Filter
}

func (o *QueryRequestWithOptions) GetGroupBy() []string {
	if o == nil {
		return nil
	}
	return o.GroupBy
}

func (o *QueryRequestWithOptions) GetIncludeCursor() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeCursor
}

func (o *QueryRequestWithOptions) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *QueryRequestWithOptions) GetOrder() []Order {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *QueryRequestWithOptions) GetProject() []Projection {
	if o == nil {
		return nil
	}
	return o.Project
}

func (o *QueryRequestWithOptions) GetQueryOptions() *QueryOptions {
	if o == nil {
		return nil
	}
	return o.QueryOptions
}

func (o *QueryRequestWithOptions) GetResolution() string {
	if o == nil {
		return ""
	}
	return o.Resolution
}

func (o *QueryRequestWithOptions) GetStartTime() string {
	if o == nil {
		return ""
	}
	return o.StartTime
}

func (o *QueryRequestWithOptions) GetVirtualFields() []VirtualColumn {
	if o == nil {
		return nil
	}
	return o.VirtualFields
}
