// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

// SourceInfo - Result sources will typically be the names of a datasets that were searched,
// but may be expanded to other things in the future.
type SourceInfo struct {
	Name *string `json:"name,omitempty"`
}

func (o *SourceInfo) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
