// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Columns struct {
}

// Table - The tabular result format can be enabled via APLQueryParams.ResultFormat or QueryParams.ResultFormat.
type Table struct {
	// The standard mode of operation for Kirby is to create buckets on the _time column,
	Buckets *BucketInfo `json:"buckets,omitempty"`
	// Columns contain a series of arrays with the raw result data.
	// The columns here line up with the fields in the Fields array.
	Columns [][]Columns `json:"columns,omitempty"`
	// Fields contain information about the fields included in these results.
	// The order of the fields match up with the order of the data in Columns.
	Fields []FieldInfo `json:"fields,omitempty"`
	// Groups specifies which grouping operations has been performed on the results.
	Groups []GroupInfo `json:"groups,omitempty"`
	// Name is the name assigned to this table. Defaults to "0". The name "_totals" is reserved for system use.
	Name *string `json:"name,omitempty"`
	// Order echoes the ordering clauses that was used to sort the results.
	Order []Order    `json:"order,omitempty"`
	Range *RangeInfo `json:"range,omitempty"`
	// Sources contain the names of the datasets that contributed data to these results.
	Sources []SourceInfo `json:"sources,omitempty"`
}

func (o *Table) GetBuckets() *BucketInfo {
	if o == nil {
		return nil
	}
	return o.Buckets
}

func (o *Table) GetColumns() [][]Columns {
	if o == nil {
		return nil
	}
	return o.Columns
}

func (o *Table) GetFields() []FieldInfo {
	if o == nil {
		return nil
	}
	return o.Fields
}

func (o *Table) GetGroups() []GroupInfo {
	if o == nil {
		return nil
	}
	return o.Groups
}

func (o *Table) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Table) GetOrder() []Order {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *Table) GetRange() *RangeInfo {
	if o == nil {
		return nil
	}
	return o.Range
}

func (o *Table) GetSources() []SourceInfo {
	if o == nil {
		return nil
	}
	return o.Sources
}
