// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Timeseries struct {
	Series []Interval   `json:"series,omitempty"`
	Totals []EntryGroup `json:"totals,omitempty"`
}

func (o *Timeseries) GetSeries() []Interval {
	if o == nil {
		return nil
	}
	return o.Series
}

func (o *Timeseries) GetTotals() []EntryGroup {
	if o == nil {
		return nil
	}
	return o.Totals
}
