// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type TrimOptions struct {
	MaxDuration string `json:"maxDuration"`
}

func (o *TrimOptions) GetMaxDuration() string {
	if o == nil {
		return ""
	}
	return o.MaxDuration
}
