// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type UpdateDataset struct {
	Description *string `json:"description,omitempty"`
}

func (o *UpdateDataset) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}
