// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type User struct {
	// User email address
	Email string `json:"email"`
	// Unique ID
	ID   string `json:"id"`
	Name string `json:"name"`
	// array<string> of permission names
	Permissions []string `json:"permissions"`
	Role        string   `json:"role"`
}

func (o *User) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *User) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *User) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *User) GetPermissions() []string {
	if o == nil {
		return []string{}
	}
	return o.Permissions
}

func (o *User) GetRole() string {
	if o == nil {
		return ""
	}
	return o.Role
}
