// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type VirtualColumn struct {
	Alias string `json:"alias"`
	Expr  string `json:"expr"`
}

func (o *VirtualColumn) GetAlias() string {
	if o == nil {
		return ""
	}
	return o.Alias
}

func (o *VirtualColumn) GetExpr() string {
	if o == nil {
		return ""
	}
	return o.Expr
}
