// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"axiom-go/models/components"
)

type CreateAnnotationResponse struct {
	HTTPMeta components.HTTPMetadata
	// The new annotation
	Annotation *components.Annotation
}

func (o *CreateAnnotationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateAnnotationResponse) GetAnnotation() *components.Annotation {
	if o == nil {
		return nil
	}
	return o.Annotation
}
