// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"axiom-go/models/components"
)

type DeleteAnnotationRequest struct {
	// The id of the annotation.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteAnnotationRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeleteAnnotationResponse struct {
	HTTPMeta components.HTTPMetadata
}

func (o *DeleteAnnotationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
