// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"axiom/models/components"
)

type DeleteDatasetRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteDatasetRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeleteDatasetResponse struct {
	HTTPMeta components.HTTPMetadata
}

func (o *DeleteDatasetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
