// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"axiom-go/models/components"
)

type GetAnnotationRequest struct {
	// The id of the annotation.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetAnnotationRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetAnnotationResponse struct {
	HTTPMeta components.HTTPMetadata
	// The annotation with the given id.
	Annotation *components.Annotation
}

func (o *GetAnnotationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAnnotationResponse) GetAnnotation() *components.Annotation {
	if o == nil {
		return nil
	}
	return o.Annotation
}
