// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"axiom/models/components"
)

type GetDatasetRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetDatasetRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetDatasetResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	DatasetSpec *components.DatasetSpec
}

func (o *GetDatasetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetDatasetResponse) GetDatasetSpec() *components.DatasetSpec {
	if o == nil {
		return nil
	}
	return o.DatasetSpec
}
