// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"axiom/models/components"
	"encoding/json"
	"fmt"
)

type Format string

const (
	FormatLegacy  Format = "legacy"
	FormatTabular Format = "tabular"
)

func (e Format) ToPointer() *Format {
	return &e
}

func (e *Format) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "legacy":
		fallthrough
	case "tabular":
		*e = Format(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Format: %v", v)
	}
}

type QueryAplRequest struct {
	Format     Format  `queryParam:"style=form,explode=true,name=format"`
	SaveAsKind *string `queryParam:"style=form,explode=true,name=saveAsKind"`
	// when saveAsKind is true, this parameter indicates the id of the associated dataset
	ID                    *string                          `queryParam:"style=form,explode=true,name=id"`
	APLRequestWithOptions components.APLRequestWithOptions `request:"mediaType=application/json"`
}

func (o *QueryAplRequest) GetFormat() Format {
	if o == nil {
		return Format("")
	}
	return o.Format
}

func (o *QueryAplRequest) GetSaveAsKind() *string {
	if o == nil {
		return nil
	}
	return o.SaveAsKind
}

func (o *QueryAplRequest) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *QueryAplRequest) GetAPLRequestWithOptions() components.APLRequestWithOptions {
	if o == nil {
		return components.APLRequestWithOptions{}
	}
	return o.APLRequestWithOptions
}

type QueryAplResponse struct {
	HTTPMeta components.HTTPMetadata
	// Successful APL result
	AplResult *components.AplResult
	Headers   map[string][]string
}

func (o *QueryAplResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *QueryAplResponse) GetAplResult() *components.AplResult {
	if o == nil {
		return nil
	}
	return o.AplResult
}

func (o *QueryAplResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
