// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"axiom/models/components"
)

type TrimDatasetRequest struct {
	ID          string                 `pathParam:"style=simple,explode=false,name=id"`
	TrimOptions components.TrimOptions `request:"mediaType=application/json"`
}

func (o *TrimDatasetRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *TrimDatasetRequest) GetTrimOptions() components.TrimOptions {
	if o == nil {
		return components.TrimOptions{}
	}
	return o.TrimOptions
}

type TrimDatasetResponse struct {
	HTTPMeta components.HTTPMetadata
	// TrimResult
	TrimResult *components.TrimResult
}

func (o *TrimDatasetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TrimDatasetResponse) GetTrimResult() *components.TrimResult {
	if o == nil {
		return nil
	}
	return o.TrimResult
}
