// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"axiom-go/models/components"
)

type UpdateAnnotationRequest struct {
	// The id of the annotation.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The fields to update.
	BaseAnnotation components.BaseAnnotation `request:"mediaType=application/json"`
}

func (o *UpdateAnnotationRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateAnnotationRequest) GetBaseAnnotation() components.BaseAnnotation {
	if o == nil {
		return components.BaseAnnotation{}
	}
	return o.BaseAnnotation
}

type UpdateAnnotationResponse struct {
	HTTPMeta components.HTTPMetadata
	// The updated annotation.
	Annotation *components.Annotation
}

func (o *UpdateAnnotationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateAnnotationResponse) GetAnnotation() *components.Annotation {
	if o == nil {
		return nil
	}
	return o.Annotation
}
