// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"axiom/models/components"
)

type UpdateDatasetRequest struct {
	ID            string                   `pathParam:"style=simple,explode=false,name=id"`
	UpdateDataset components.UpdateDataset `request:"mediaType=application/json"`
}

func (o *UpdateDatasetRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateDatasetRequest) GetUpdateDataset() components.UpdateDataset {
	if o == nil {
		return components.UpdateDataset{}
	}
	return o.UpdateDataset
}

type UpdateDatasetResponse struct {
	HTTPMeta components.HTTPMetadata
	// DatasetSpec
	DatasetSpec *components.DatasetSpec
}

func (o *UpdateDatasetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateDatasetResponse) GetDatasetSpec() *components.DatasetSpec {
	if o == nil {
		return nil
	}
	return o.DatasetSpec
}
